#!/bin/bash
# Copies M Bakeri's photos into ./images so the site serves them from your GitHub repo.
mkdir -p images
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2020/04/maca-post-1a.jpg" -o "images/maca-post-1a.jpg" && echo "ok  maca-post-1a.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2022/08/capuccino.jpg" -o "images/capuccino.jpg" && echo "ok  capuccino.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2022/08/mbak-side-panel-1.jpg" -o "images/mbak-side-panel-1.jpg" && echo "ok  mbak-side-panel-1.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2023/07/salmon-quiche-slice.jpg" -o "images/salmon-quiche-slice.jpg" && echo "ok  salmon-quiche-slice.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2023/08/cakes-1a.jpg" -o "images/cakes-1a.jpg" && echo "ok  cakes-1a.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/07/chris-expand-1a.jpg" -o "images/chris-expand-1a.jpg" && echo "ok  chris-expand-1a.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/bottle-water.jpg" -o "images/bottle-water.jpg" && echo "ok  bottle-water.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/cappu.jpg" -o "images/cappu.jpg" && echo "ok  cappu.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/drinks.jpg" -o "images/drinks.jpg" && echo "ok  drinks.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/drip.png" -o "images/drip.png" && echo "ok  drip.png"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/flatwhite.jpg" -o "images/flatwhite.jpg" && echo "ok  flatwhite.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/hotchoc.jpg" -o "images/hotchoc.jpg" && echo "ok  hotchoc.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/ice-tea.jpg" -o "images/ice-tea.jpg" && echo "ok  ice-tea.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/iced-2.jpg" -o "images/iced-2.jpg" && echo "ok  iced-2.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/iced-cream.jpg" -o "images/iced-cream.jpg" && echo "ok  iced-cream.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/iced-red.jpg" -o "images/iced-red.jpg" && echo "ok  iced-red.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/latte.jpg" -o "images/latte.jpg" && echo "ok  latte.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/macchiato.jpg" -o "images/macchiato.jpg" && echo "ok  macchiato.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/old-milk.jpg" -o "images/old-milk.jpg" && echo "ok  old-milk.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/redeye.jpg" -o "images/redeye.jpg" && echo "ok  redeye.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2024/08/sparkling.jpg" -o "images/sparkling.jpg" && echo "ok  sparkling.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/2025/06/smoothie-green-goddess-1a.webp" -o "images/smoothie-green-goddess-1a.webp" && echo "ok  smoothie-green-goddess-1a.webp"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/elementor/thumbs/bagette-qywo0pi8j90k1e765qha7h4pq7l8hpnrz3azgd3tnk.png" -o "images/bagette-qywo0pi8j90k1e765qha7h4pq7l8hpnrz3azgd3tnk.png" && echo "ok  bagette-qywo0pi8j90k1e765qha7h4pq7l8hpnrz3azgd3tnk.png"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/elementor/thumbs/mb-wrap-1a-r76f5pcx1u66mvle1y5hb8pu6nsevgwvab00b0ltb4.webp" -o "images/mb-wrap-1a-r76f5pcx1u66mvle1y5hb8pu6nsevgwvab00b0ltb4.webp" && echo "ok  mb-wrap-1a-r76f5pcx1u66mvle1y5hb8pu6nsevgwvab00b0ltb4.webp"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/elementor/thumbs/pistachio-cookies-qywo0pi8a1gwsz9bvivv1rqcwwou33pdyqzvkzyyfs.jpg" -o "images/pistachio-cookies-qywo0pi8a1gwsz9bvivv1rqcwwou33pdyqzvkzyyfs.jpg" && echo "ok  pistachio-cookies-qywo0pi8a1gwsz9bvivv1rqcwwou33pdyqzvkzyyfs.jpg"
curl -fsSL "https://mbakerillc.com/wp-content/uploads/elementor/thumbs/swwets-1a-qywo0rdwwharrstcgbvclz0yb59w8ujztd7vrtzm3k.jpg" -o "images/swwets-1a-qywo0rdwwharrstcgbvclz0yb59w8ujztd7vrtzm3k.jpg" && echo "ok  swwets-1a-qywo0rdwwharrstcgbvclz0yb59w8ujztd7vrtzm3k.jpg"
